name: CI Módulo 26 - Relatório

on:
  push:
    branches: [ "exercicio-modulo-23" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true 

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20 

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test || true # O "|| true" garante que ele gere o relatório mesmo se um teste falhar

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './mochawesome-report'